backup redis to email

diff --git a/.github/workflows/deploy-common-cron.yml b/.github/workflows/deploy-common-cron.yml
--- a/.github/workflows/deploy-common-cron.yml
+++ b/.github/workflows/deploy-common-cron.yml
@@ -73,6 +73,8 @@ jobs:
           EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
           REDIS_KEY: ${{ secrets.REDIS_KEY }}
           SENDGRID_TEMPLATE_ID: ${{ secrets.SENDGRID_TEMPLATE_ID }}
+          STOCKS_TELEGRAM_ADMIN_BOT_TOKEN: ${{ secrets.STOCKS_TELEGRAM_ADMIN_BOT_TOKEN }}
+          STOCKS_TELEGRAM_ADMIN_ID: ${{ secrets.STOCKS_TELEGRAM_ADMIN_ID }}
         run: |
           ssh production <<-EOF
           
@@ -84,6 +86,8 @@ jobs:
           EMAIL_SENDER=\$3
           REDIS_KEY=\$4
           SENDGRID_TEMPLATE_ID=\$5
+          STOCKS_TELEGRAM_BOT_TOKEN=\$6
+          STOCKS_TELEGRAM_CHANNEL_ID=\$7
           
           if [ -z "\$SENDGRID_API_KEY"  ];
           then
@@ -110,26 +114,89 @@ jobs:
               echo "template id is required"
               exit 1
           fi
+          if [ -z "\$STOCKS_TELEGRAM_BOT_TOKEN"  ];
+          then
+              echo "telegram bot token is required"
+              exit 1
+          fi
+          if [ -z "\$STOCKS_TELEGRAM_CHANNEL_ID"  ];
+          then
+              echo "telegram channel id is required"
+              exit 1
+          fi
           
-          FROM_NAME="han"
-          SUBJECT="market-data-notification: tradingview redis"
+          REDIS_DATA_PATH="/var/lib/redis"
+          REDIS_BACKUP_FILE_NAME="redis_backup_\$(date "+%Y-%m-%dT%H%M%S%z").zip"
           
-          redis_data=\$(echo "zrange \$REDIS_KEY -1 -1 withscores" | redis-cli)
-          redis_data=\$(echo \$redis_data | sed -e "s/\"/'/g" )
+          function backup_redis() {
+            sudo sh -c "cd \$REDIS_DATA_PATH && zip -r \$REDIS_BACKUP_FILE_NAME ."
+            sudo mv "\$REDIS_DATA_PATH/\$REDIS_BACKUP_FILE_NAME" .
+          }
           
-          maildata='{"personalizations": [{"to": [{"email": "'\${EMAIL_RECIPIENT}'"}], "dynamic_template_data": { "redis_data": "'\${redis_data}'" } }],"from": {"email": "'\${EMAIL_SENDER}'",
-              "name": "'\${FROM_NAME}'"},"subject": "'\${SUBJECT}'", "template_id": "'${SENDGRID_TEMPLATE_ID}'"}'
+          function cleanup() {
+            sudo rm -rf \$REDIS_BACKUP_FILE_NAME
+          }
           
-          curl --request POST \
-            --url https://api.sendgrid.com/v3/mail/send \
-            --header 'Authorization: Bearer '\$SENDGRID_API_KEY \
-            --header 'Content-Type: application/json' \
-            --data "\$maildata"
+          function send_mail() {
+            redis_data=\$(echo "zrange \$REDIS_KEY -1 -1 withscores" | redis-cli)
+            redis_data=\$(echo \$redis_data | sed -e "s/\"/'/g")
+            unix_timestamp=\$(echo \$redis_data | sed -r "s/.* ([0-9]+)/\\1/g")
+            redis_data_date=\$(date -d @\${unix_timestamp} +%Y-%m-%d)
+          
+            FROM_NAME="han@market-data-notification"
+
+            backup_file=\$(cat \$REDIS_BACKUP_FILE_NAME | base64 -w0)
+          
+            # TODO: write in python?
+            # https://docs.sendgrid.com/api-reference/mail-send/mail-send
+            maildata='{"personalizations":
+              [
+                {
+                  "to": [{"email": "'\${EMAIL_RECIPIENT}'"}],
+                  "dynamic_template_data": {
+                    "redis_data": "'\${redis_data}'",
+                    "redis_data_date": "'\${redis_data_date}'"
+                  }
+                }
+              ],
+              "from": {
+                "email": "'\${EMAIL_SENDER}'",
+                "name": "'\${FROM_NAME}'"
+              },
+              "template_id": "'\${SENDGRID_TEMPLATE_ID}'",
+              "attachments": [
+                {
+                  "content": "'\${backup_file}'",
+                  "filename": "'\${REDIS_BACKUP_FILE_NAME}'",
+                  "type": "application/zip",
+                  "disposition": "attachment"
+                }
+              ]
+            }'
+          
+            curl --request POST \
+              --url https://api.sendgrid.com/v3/mail/send \
+              --header 'Authorization: Bearer '\$SENDGRID_API_KEY \
+              --header 'Content-Type: application/json' \
+              --data "\$maildata"
+          }
+          
+          function notify_telegram() {
+            now=\$(date +%Y-%m-%dT%H:%M:%S)
+            text=\$(echo "\[Redis report\] Market data notification redis report backed up to email at \$now." | sed 's~[[:blank:]]~%20~g')
+            curl "https://api.telegram.org/bot\${STOCKS_TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=\${STOCKS_TELEGRAM_CHANNEL_ID}&text=\$text"
+          }
+          
+          backup_redis
+          send_mail
+          notify_telegram
+          cleanup
           EOF2
 
           chmod +x redis_report.sh
           crontab -l > mycron
-          echo "0 13,14 * * 0-6 ./redis_report.sh $SENDGRID_API_KEY $EMAIL_RECIPIENT $EMAIL_SENDER $REDIS_KEY $SENDGRID_TEMPLATE_ID > common.log 2>&1" >> mycron
+          # around 4pm local time
+          echo "5 20,21 * * 0-6 ./redis_report.sh $SENDGRID_API_KEY $EMAIL_RECIPIENT $EMAIL_SENDER $REDIS_KEY $SENDGRID_TEMPLATE_ID $STOCKS_TELEGRAM_ADMIN_BOT_TOKEN $STOCKS_TELEGRAM_ADMIN_ID > common.log 2>&1" >> mycron
           
           mv mycron mycron.temp
           cat mycron.temp | sort | uniq > mycron
