Fix redis cron
Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

Fix redis cron

diff --git a/.github/workflows/deploy-common-cron.yml b/.github/workflows/deploy-common-cron.yml
--- a/.github/workflows/deploy-common-cron.yml
+++ b/.github/workflows/deploy-common-cron.yml
@@ -68,21 +68,68 @@ jobs:
           REDIS_KEY: ${{ secrets.REDIS_KEY }}
         run: |
           ssh production <<-EOF
+          
+          cat <<'EOF2' | tee redis_report.sh > /dev/null
+          #! /bin/bash
+          
+          SENDGRID_API_KEY=\$1
+          EMAIL_RECIPIENT=\$2
+          EMAIL_SENDER=\$3
+          REDIS_KEY=\$4
+          
+          if [ -z "\$SENDGRID_API_KEY"  ];
+          then
+              echo "send grid api is required"
+              exit 1
+          fi
+          if [ -z "\$EMAIL_RECIPIENT"  ];
+          then
+              echo "email recipient is required"
+              exit 1
+          fi
+          if [ -z "\$EMAIL_SENDER"  ];
+          then
+              echo "email sender is required"
+              exit 1
+          fi
+          if [ -z "\$REDIS_KEY"  ];
+          then
+              echo "redis key is required"
+              exit 1
+          fi
+          
+          FROM_NAME="han"
+          SUBJECT="market-data-notification: tradingview redis"
+          
+          redis_data=\$(echo "zrange \$REDIS_KEY 0 -1 withscores" | redis-cli)
+          redis_data=\$(echo \$redis_data | sed -e "s/\"/'/g" )
+          bodyHTML="<p><strong>Redis data for tradingview</strong></p><pre>\${redis_data}</pre>"
+          
+          maildata='{"personalizations": [{"to": [{"email": "'\${EMAIL_RECIPIENT}'"}]}],"from": {"email": "'\${EMAIL_SENDER}'",
+              "name": "'\${FROM_NAME}'"},"subject": "'\${SUBJECT}'","content": [{"type": "text/html", "value": "'\${bodyHTML}'"}]}'
+          
+          curl --request POST \
+            --url https://api.sendgrid.com/v3/mail/send \
+            --header 'Authorization: Bearer '\$SENDGRID_API_KEY \
+            --header 'Content-Type: application/json' \
+            --data "\$maildata"
+          EOF2
 
+          sudo chmod +x redis_report.sh
           crontab -l > mycron
-          echo "45 12,13 * * 0-6 src/job/redis_report.sh $SENDGRID_API_KEY $EMAIL_RECIPIENT $EMAIL_SENDER $REDIS_KEY > common.log 2>&1" >> mycron
+          echo "45 12 * * 0-6 ./redis_report.sh $SENDGRID_API_KEY $EMAIL_RECIPIENT $EMAIL_SENDER $REDIS_KEY > common.log 2>&1" >> mycron
           
           mv mycron mycron.bak
           cat mycron.bak | sort | uniq > mycron
           crontab mycron
-          echo $?
+          echo \$?
           EOF
           
-          if [ $? -ne 0 ]
+          if [ \$? -ne 0 ]
           then
             rm -rf ~/.ssh
             echo "error"
-            exit 1sadsadas
+            exit 1
           else
             echo "all good"
           fi
