Fix heredoc

diff --git a/.github/workflows/deploy-cron.yml b/.github/workflows/deploy-cron.yml
--- a/.github/workflows/deploy-cron.yml
+++ b/.github/workflows/deploy-cron.yml
@@ -1,9 +1,5 @@
 name: Deploy cron
 on:
-  push:
-    branches:
-      - feature/*
-      - master
   workflow_run:
     workflows: [Test and build]
     types:
@@ -18,9 +14,9 @@ on:
         default: 'info'
         type: choice
         options:
-        - info
-        - warning
-        - debug
+          - info
+          - warning
+          - debug
 env:
   SSH_USER: ${{ secrets.SSH_USER }}
   SSH_HOST: ${{ secrets.SSH_HOST }}
@@ -69,22 +65,47 @@ jobs:
             IdentityFile ~/.ssh/market_data_notification_rsa
             StrictHostKeyChecking no
           EOF
-      - name: SSH into server, set crontab
+      - name: SSH into server, set my_crontab
         id: deploy
         run: |
-          ssh production << EOF
-            cat << FOE | sudo tee market_data_notification.sh >/dev/null
-            #! /bin/bash
+          ssh production <<-'EOF'
+          cat << 'EOF2' | sudo tee market_data_notification.sh > /dev/null
+          #! /bin/bash
 
-            docker exec market_data_notification bash << EOF
-            . $(poetry env info --path)/bin/activate
-            poetry run python3 src/job/market_data_notification.py
-            FOE
-            chmod +x ./market_data_notification.sh
+          app_name=$1
+          file_path=$2
+          if [ -z "$app_name" ];
+          then
+            echo "app name is required"
+            exit 1
+          fi
+        
+          if [ -z "$file_path" ];
+          then
+            echo "file path is required"
+            exit 1
+          fi
           
-            crontab <<< "30 12,13 * * * ./market_data_notification.sh  >> market_data_notification.log 2>&1"
-            echo \$?
+          docker exec -i $app_name bash << EOF3
+          . $(poetry env info --path)/bin/activate
+          poetry run python3 $file_path
+          EOF3
+          
+          EOF2
+
+          sudo chmod +x market_data_notification.sh
+          crontab <<< "30 12,13 * * * ./market_data_notification.sh market_data_notification src/job/market_data_notification.py > market_data_notification.log 2>&1"
+          echo $?
           EOF
+          
+          if [ $? -ne 0 ]
+          then
+            rm -rf ~/.ssh
+            echo "error"
+            exit 1
+          else
+            echo "all good"
+          fi
           rm -rf ~/.ssh
   notify_unsuccessful:
     runs-on: ubuntu-latest
